### ISSUE TITLE
How to use relative energy / relative mass of particles (documentation question)

### ISSUE THREAD

**Issue by cjnqt** [alexander-stolz/limioptic#5]
Hi,

How should the parameter `relative energy deviation` / `relative mass deviation` of the particle be used? 
For example, let's say we want to add a single proton and a single deuteron with the same energy. The deuteron has ~2 times the mass of the proton. What's the parameter for the deuteron's relative mass in permille – should it be 2000? 

### Proton
Particle(x, a, y, b, 0, 0)

### Deuteron 
Particle(x, a, y, b, 0, 2000) <-- Relative mass is 2 times the proton's mass?

**Comment by alexander-stolz** [comment]
The formula in this case is `(2u/1u - 1) * 1000 permille`, so the value is 1000.

Because both have the same energy, the energy deviation is `(E/E - 1) * 1000 = (1 - 1) * 1000 = 0`.

So:
```
proton:    Particle(x, a, y, b, 0, 0)
deuteron:  Particle(x, a, y, b, 0, 1000)
```
Or if you have a beam with some scattering you can use `Beam()` instead.

**Comment by cjnqt** [comment]
Great!
